### ISSUE TITLE
TODO: Function create_matrix() could be made to run faster

### ISSUE THREAD

**Issue by ghosoya** [ghosoya/ludwig#1]
The function to create the design matrix for the multivariate logistic regression does not scale very well in terms of speed with the number of nodes. This could be improved.

**Comment by abeeisnotabug** [comment]
I optimized the algorithm in R and implemented it again in C++ via Rcpp. Since this did not give significantly better results, we kept the algorithm strictly in R for package simplicity.

**Comment by ghosoya** [comment]
Thanks a lot! I am going to update the repository with the new exciting additions in the near future!
